### ISSUE TITLE
practice-type-screen-ui

### ISSUE THREAD

**Issue by ahmadkhandev** [nooralibutt/playon#17]
Work on the PracticeTypeScreen ui

zpl://screen?pid=6142de966a8623564ee9a1ed&sid=6142e041fc97422118d42865

**Comment by Tayyab-98** [comment]
<img src="https://user-images.githubusercontent.com/89379559/135043375-2856b574-5ed0-4caa-a832-a8b3651b0c3a.png" width="200"/>
