### ISSUE TITLE
game-kind-screen-ui

### ISSUE THREAD

**Issue by ahmadkhandev** [nooralibutt/playon#5]
Work on the UI of game_kind_screen

Here's the link to that:
zpl://screen?sid=6142e0433fa54c294b332592&pid=6142de966a8623564ee9a1ed

Use the Zeplin credentials provided in the Teams group of PlayOn.

**Comment by Tayyab-98** [comment]
<img src="https://user-images.githubusercontent.com/89379559/135042258-fbb94ac7-7128-49fc-b156-1bfb70b449b3.png" width="200" height="400" />
